app.constant('routeService',{
        myPurse:'/mp',
        consoleJ:'/cs',
        safe:'/sf',
        recharge:'/recharges',
        real:'/realview',
        card:'/bindcard',
        login:'/login',
        resuc:'/resuc'
    });